// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiqEgCPVdPsyKX2snB69VFf8ZMlyXHFbw',
    appId: '1:115115884918:web:6287db6b59b89002ea7a57',
    messagingSenderId: '115115884918',
    projectId: 'bdbichos',
    authDomain: 'bdbichos.firebaseapp.com',
    storageBucket: 'bdbichos.firebasestorage.app',
    measurementId: 'G-GPJZL8RPY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB49JEkSRZnoNDZopDU2pAaTvOJYCZT06U',
    appId: '1:115115884918:android:03c315b5e86f525bea7a57',
    messagingSenderId: '115115884918',
    projectId: 'bdbichos',
    storageBucket: 'bdbichos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiFIt3FDDUc2qIX6oQR0SU4Dh_e8_GtNk',
    appId: '1:115115884918:ios:c79d12e976d7ab13ea7a57',
    messagingSenderId: '115115884918',
    projectId: 'bdbichos',
    storageBucket: 'bdbichos.firebasestorage.app',
    iosBundleId: 'com.example.appBichos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiFIt3FDDUc2qIX6oQR0SU4Dh_e8_GtNk',
    appId: '1:115115884918:ios:c79d12e976d7ab13ea7a57',
    messagingSenderId: '115115884918',
    projectId: 'bdbichos',
    storageBucket: 'bdbichos.firebasestorage.app',
    iosBundleId: 'com.example.appBichos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiqEgCPVdPsyKX2snB69VFf8ZMlyXHFbw',
    appId: '1:115115884918:web:30504d41260ffd02ea7a57',
    messagingSenderId: '115115884918',
    projectId: 'bdbichos',
    authDomain: 'bdbichos.firebaseapp.com',
    storageBucket: 'bdbichos.firebasestorage.app',
    measurementId: 'G-EXJ4KVBQZ9',
  );
}
