name: Build iOS

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-26

    defaults:
      run:
        working-directory: app_bichos

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Ver versiones
        run: |
          flutter --version
          xcodebuild -version
          xcrun --sdk iphoneos --show-sdk-version

      - name: Verificar proyecto
        run: |
          pwd
          test -f pubspec.yaml
          test -d ios/Runner.xcodeproj
          echo "Proyecto Flutter encontrado correctamente"

      - name: Instalar dependencias Flutter
        run: flutter pub get

      - name: Analizar proyecto
        run: flutter analyze
        continue-on-error: true

      - name: Compilar iOS Release
        run: |
          flutter build ios \
            --release \
            --no-codesign

      - name: Verificar Runner.app
        run: |
          test -d build/ios/iphoneos/Runner.app
          ls -la build/ios/iphoneos/Runner.app
          echo "Runner.app generado correctamente"

      - name: Crear IPA
        run: |
          rm -rf ../../Payload
          mkdir ../../Payload

          cp -R build/ios/iphoneos/Runner.app ../../Payload/Runner.app

          cd ../..

          ditto \
            -c \
            -k \
            --sequesterRsrc \
            --keepParent \
            Payload \
            AppBichos-unsigned.ipa

      - name: Verificar estructura IPA
        working-directory: .
        run: |
          echo "=== CONTENIDO DEL IPA ==="
          unzip -l AppBichos-unsigned.ipa | head -80

          if unzip -l AppBichos-unsigned.ipa | grep -q "Payload/Runner.app/Runner.app"; then
            echo "ERROR: Runner.app esta duplicado"
            exit 1
          fi

          echo "IPA empaquetado correctamente"

      - name: Guardar IPA
        uses: actions/upload-artifact@v4
        with:
          name: AppBichos-iOS-unsigned
          path: AppBichos-unsigned.ipa
          retention-days: 7