name: Build iOS

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-26

    defaults:
      run:
        working-directory: app_bichos

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Ver versiones
        run: |
          flutter --version
          xcodebuild -version
          xcrun --sdk iphoneos --show-sdk-version

      - name: Verificar proyecto
        run: |
          test -f pubspec.yaml
          test -d ios/Runner.xcodeproj
          echo "Proyecto encontrado"

      - name: Instalar dependencias
        run: flutter pub get

      - name: Compilar iOS Release
        run: |
          flutter build ios \
            --release \
            --no-codesign

      - name: Verificar Runner.app
        run: |
          test -d build/ios/iphoneos/Runner.app
          echo "Runner.app generado correctamente"

      - name: Crear IPA
        run: |
          rm -rf "$RUNNER_TEMP/Payload"
          mkdir -p "$RUNNER_TEMP/Payload"

          cp -R \
            build/ios/iphoneos/Runner.app \
            "$RUNNER_TEMP/Payload/Runner.app"

          cd "$RUNNER_TEMP"

          ditto \
            -c \
            -k \
            --sequesterRsrc \
            --keepParent \
            Payload \
            "$GITHUB_WORKSPACE/AppBichos-unsigned.ipa"

          echo "IPA creado en:"
          ls -lh "$GITHUB_WORKSPACE/AppBichos-unsigned.ipa"

      - name: Verificar IPA
        working-directory: .
        run: |
          test -f "$GITHUB_WORKSPACE/AppBichos-unsigned.ipa"

          unzip -l "$GITHUB_WORKSPACE/AppBichos-unsigned.ipa" | head -60

          if unzip -l "$GITHUB_WORKSPACE/AppBichos-unsigned.ipa" | grep -q "Payload/Runner.app/Runner.app"; then
            echo "ERROR: Runner.app duplicado"
            exit 1
          fi

          echo "IPA correcto"

      - name: Guardar IPA
        uses: actions/upload-artifact@v4
        with:
          name: AppBichos-iOS-unsigned
          path: ${{ github.workspace }}/AppBichos-unsigned.ipa
          if-no-files-found: error
          retention-days: 7